/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Apply: (typeof import('./components/Apply.vue'))['default']
    copy: (typeof import('./components/Enquiry copy.vue'))['default']
    Description: (typeof import('./components/Description.vue'))['default']
    Enquiry: (typeof import('./components/Enquiry.vue'))['default']
    Footer: (typeof import('./components/Footer.vue'))['default']
    Header: (typeof import('./components/Header.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Settings: (typeof import('./components/Settings.vue'))['default']
    VanBadge: (typeof import('vant/es'))['Badge']
    VanButton: (typeof import('vant/es'))['Button']
    VanCalendar: (typeof import('vant/es'))['Calendar']
    VanCell: (typeof import('vant/es'))['Cell']
    VanCellGroup: (typeof import('vant/es'))['CellGroup']
    VanCheckbox: (typeof import('vant/es'))['Checkbox']
    VanCol: (typeof import('vant/es'))['Col']
    VanField: (typeof import('vant/es'))['Field']
    VanIcon: (typeof import('vant/es'))['Icon']
    VanImage: (typeof import('vant/es'))['Image']
    VanLoading: (typeof import('vant/es'))['Loading']
    VanNavBar: (typeof import('vant/es'))['NavBar']
    VanPopup: (typeof import('vant/es'))['Popup']
    VanRadio: (typeof import('vant/es'))['Radio']
    VanRadioGroup: (typeof import('vant/es'))['RadioGroup']
    VanRow: (typeof import('vant/es'))['Row']
    VanSlider: (typeof import('vant/es'))['Slider']
    VanSwitch: (typeof import('vant/es'))['Switch']
    VanTab: (typeof import('vant/es'))['Tab']
    VanTabs: (typeof import('vant/es'))['Tabs']
  }
}
